package UI;


import Backend.PasswordUtils;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class AuthWindow {
    public JPanel authPanel;
    public JButton authButton;
    private JTextField userNameField;
    private JPasswordField passwordField;
    private JPanel fieldsPanel;

    public static Integer numberOfIncorrectInputs = 0;

    public AuthWindow() {
        JMenuBar menuBar = new JMenuBar();
        JMenu menuOption = new JMenu("About");
        JMenuItem open = new JMenuItem(new AboutAction());
        menuOption.add(open);
        menuBar.add(menuOption);
        authPanel.add(menuBar, BorderLayout.NORTH);

        authButton.addActionListener(action -> {
            String passwordString = new String(passwordField.getPassword());
            if (passwordString.contains(" ")) {
                JOptionPane.showMessageDialog(null, "Space symbol is not allowed in password!");
            } else {
                String userName = userNameField.getText();
                if (PasswordUtils.PASSWORDS.containsKey(userName)) {
                    if (inputPasswordIsCorrectOrSetNew(passwordString, userName)) {
                        numberOfIncorrectInputs = 0;
                        PasswordUtils.currentUser = PasswordUtils.PASSWORDS.get(userName);

                        if (PasswordUtils.currentUser.isBlocked()) {
                            JOptionPane.showMessageDialog(null, "Your account is blocked!");
                        } else if (userName.equals(PasswordUtils.ADMIN_NAME)) {
                            final JDialog adminOptionsWindow = new JDialog(new JFrame("Admin options"), true);

                            adminOptionsWindow.addWindowListener(new WindowAdapter() {
                                @Override
                                public void windowClosing(WindowEvent e) {
                                    passwordField.setText("");
                                    e.getWindow().dispose();
                                }
                            });

                            adminOptionsWindow.setContentPane(new AdminOptionsWindow().getAdminOptionsPanel());
                            adminOptionsWindow.pack();
                            adminOptionsWindow.setSize(200, 200);
                            adminOptionsWindow.setMaximumSize(new Dimension(200, 200));

                            adminOptionsWindow.setVisible(true);
                        } else {
                            final JDialog userOptionsWindow = new JDialog(new JFrame("User options"), true);

                            userOptionsWindow.addWindowListener(new WindowAdapter() {
                                @Override
                                public void windowClosing(WindowEvent e) {
                                    passwordField.setText("");
                                    e.getWindow().dispose();
                                }
                            });

                            userOptionsWindow.setContentPane(new UserOptionsWindow().getUserOptionsPanel());
                            userOptionsWindow.pack();
                            userOptionsWindow.setSize(200, 200);
                            userOptionsWindow.setMaximumSize(new Dimension(200, 200));

                            userOptionsWindow.setVisible(true);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Please check your password!");
                        if (++numberOfIncorrectInputs == 3) {
                            System.exit(1);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, String.format("No user with name %s", userName));
                }
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        authPanel = new JPanel();
        authPanel.setLayout(new BorderLayout(0, 0));
        fieldsPanel = new JPanel();
        fieldsPanel.setLayout(new GridLayoutManager(7, 1, new Insets(0, 0, 0, 0), -1, -1));
        authPanel.add(fieldsPanel, BorderLayout.CENTER);
        userNameField = new JTextField();
        fieldsPanel.add(userNameField, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        passwordField = new JPasswordField();
        fieldsPanel.add(passwordField, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        authButton = new JButton();
        authButton.setText("Auth");
        fieldsPanel.add(authButton, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        fieldsPanel.add(spacer1, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        fieldsPanel.add(spacer2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Username");
        fieldsPanel.add(label1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1, false));
        final JLabel label2 = new JLabel();
        label2.setText("Password");
        fieldsPanel.add(label2, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return authPanel;
    }

    private static class AboutAction extends AbstractAction {
        AboutAction() {
            putValue(NAME, "Show info");
        }

        @Override
        public void actionPerformed(ActionEvent actionEvent) {
            JOptionPane.showMessageDialog(null, "Лабораторную выполнил Анкушев А.Д.\nГруппа А-05-16\nВариант №1\n\n" +
                    "Условие №1:\nДлина не меньше минимальной длины, устанавливаемой\nадминистратором и сохраняемой в учетной записи пользователя\n" +
                    "Условие №3:\nШифрование перестановкой\n(ключ задается именем учетной записи пользователя).\n" +
                    "Условие №4:\nТип симметричного шифрования : Блочный\n" +
                    "Используемый режим шифрования : Электронная кодовая книга\nДобавление к ключу случайного значения : да\nИспользуемый алгоритм хеширования" +
                    " : MD2\nМЭИ, 2019.");
        }
    }

    private boolean inputPasswordIsCorrectOrSetNew(String passwordString, String userName) {
        String encryptedPassword = PasswordUtils.PASSWORDS.get(userName).getPassword();
        if (!userName.equals(PasswordUtils.ADMIN_NAME) && encryptedPassword.isEmpty()) {
            PasswordUtils.setUsersPassword(userName);
            return true;
        } else {
            String newEncryptedPassword = PasswordUtils.getEncryptedPassword(userName, passwordString);
            return encryptedPassword.equals(newEncryptedPassword);
        }
    }
}
